export const why_nourify = [
  {
    title: "100% Organic",
    text: "We offer a wide range of organic products, ensuring you eat clean and healthy.",
  },
  {
    title: "Fast Delivery",
    text: "Get your orders delivered on the same day, keeping them fresh always.",
  },
  {
    title: "100% Organic",
    text: "We offer a wide range of organic products, ensuring you eat clean and healthy.",
  },
  {
    title: "Fast Delivery",
    text: "Get your orders delivered on the same day, keeping them fresh always.",
  },
  {
    title: "Locally Sourced",
    text: "Our products come from local farms and bakeries, supporting the community.",
  },
  {
    title: "100% Organic",
    text: "We offer a wide range of organic products, ensuring you eat clean and healthy.",
  },
];

export const products = [
  {
    id: 1,
    name: "Garden Cucumbers",
    price: 50000,
    image: "/cucumber.svg",
    category: "pastries",
    size: "small",
    limitedOffer: false,
    expressDelivery: false,
    
  },
  {
    id: 2,
    name: "Cherry Tomatoes",
    price: 10000,
    image: "/tomatoes.svg",
    category: "pastries",
    size: "small",
    limitedOffer: true,
    expressDelivery: true,
  },
  {
    id: 3,
    name: "Fresh Cilantro",
    price: 20000,
    image: "/cilantro.svg",
    category: "pastries",
    size: "medium",
    limitedOffer: false,
    expressDelivery: true,
  },
  {
    id: 4,
    name: "Garden Cucumbers",
    price: 40000,
    image: "/cucumber.svg",
    category: "pastries",
    size: "large",
    limitedOffer: false,
    expressDelivery: true,
  },
  {
    id: 5,
    name: "Garden Cucumbers",
    price: 50000,
    image: "/cucumber.svg",
    category: "pastries",
    size: "medium",
    limitedOffer: true,
    expressDelivery: false,
  },
  {
    id: 6,
    name: "Fresh Cilantro",
    price: 50000,
    image: "/cilantro.svg",
    category: "pastries",
    size: "small",
    limitedOffer: false,
    expressDelivery: true,
  },
  {
    id: 7,
    name: "Garden Cucumbers",
    price: 50000,
    image: "/cucumber.svg",
    category: "pastries",
    size: "large",
    limitedOffer: true,
    expressDelivery: true,
  },
  {
    id: 8,
    name: "Cherry Tomatoes",
    price: 70000,
    image: "/tomatoes.svg",
    category: "pastries",
    size: "medium",
    limitedOffer: false,
    expressDelivery: true,
  },
  {
    id: 9,
    name: "Garden Cucumbers",
    price: 60000,
    image: "/cucumber.svg",
    category: "groceries",
    size: "medium",
    limitedOffer: true,
    expressDelivery: false,
    
  },
  {
    id: 10,
    name: "Cherry Tomatoes",
    price: 70000,
    image: "/tomatoes.svg",
    category: "groceries",
    size: "small",
    limitedOffer: false,
    expressDelivery: true,
  },
  {
    id: 11,
    name: "Fresh Cilantro",
    price: 30000,
    image: "/cilantro.svg",
    category: "groceries",
    size: "large",
    limitedOffer: true,
    expressDelivery: true,
  },
  {
    id: 12,
    name: "Garden Cucumbers",
    price: 10000,
    image: "/cucumber.svg",
    category: "groceries",
    size: "medium",
    limitedOffer: true,
    expressDelivery: true,
  },
  {
    id: 13,
    name: "Garden Cucumbers",
    price: 20000,
    image: "/cucumber.svg",
    category: "groceries",
    size: "small",
    limitedOffer: false,
    expressDelivery: true,
  },
  {
    id: 14,
    name: "Fresh Cilantro",
    price: 50000,
    image: "/cilantro.svg",
    category: "groceries",
    size: "small",
    limitedOffer: true,
    expressDelivery: false,
    
  },
  {
    id: 15,
    name: "Garden Cucumbers",
    price: 90000,
    image: "/cucumber.svg",
    category: "groceries",
    size: "medium",
    limitedOffer: true,
    expressDelivery: true,
  },
  {
    id: 16,
    name: "Cherry Tomatoes",
    price: 80000,
    image: "/tomatoes.svg",
    category: "groceries",
    size: "small",
    limitedOffer: false,
    expressDelivery: true,
  },
];
